export const ADD_FILES = 'ADD_FILES';
export const REMOVE_FILE = 'REMOVE_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';

export const ORDER_FORM_SEND = 'ORDER_FORM_SEND';
export const ORDER_FORM_SENT = 'ORDER_FORM_SENT';

export const VACANCIES_PENDING = 'VACANCIES_PENDING';
export const VACANCIES_FULFILLED = 'VACANCIES_FULFILLED';
export const VACANCIES_REJECTED = 'VACANCIES_REJECTED';
