export const SEND_FORM = 'SEND_FORM';
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS';
export const SEND_FORM_ERROR = 'SEND_FORM_ERROR';

export const ADD_JOB = 'ADD_JOB';
export const CHANGE_ANSWER_FORM = 'CHANGE_ANSWER_FORM';
export const SEND_ANSWER_FORM = 'SEND_ANSWER_FORM';
export const SHOW_FORM_ERRORS = 'SHOW_FORM_ERRORS';

export const ORDER_FORM_CHANGE_OPTIONS = 'ORDER_FORM_CHANGE_OPTIONS';
export const ORDER_FORM_CHANGE_CONTACTS = 'ORDER_FORM_CHANGE_CONTACTS';
export const ORDER_FORM_SHOW_ERRORS = 'ORDER_FORM_SHOW_ERRORS';
export const ORDER_FORM_CHANGE_FILES_LINK = 'ORDER_FORM_CHANGE_FILES_LINK';

export const ORDER_FORM_ADD_FILES = 'ORDER_FORM_ADD_FILES';
export const ORDER_FORM_REMOVE_FILES = 'ORDER_FORM_REMOVE_FILES';
export const ORDER_FORM_UPDATE_FILE_PROGRESS = 'ORDER_FORM_UPDATE_FILE_PROGRESS';
