export const ADD_FILES = 'ADD_FILES';
export const REMOVE_FILE = 'REMOVE_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';

export const ORDER_FORM_SEND = 'ORDER_FORM_SEND';
export const ORDER_FORM_SENT = 'ORDER_FORM_SENT';

export const REQUEST_VACANCIES = 'REQUEST_VACANCIES';
export const REJECT_VACANCIES = 'REJECT_VACANCIES';
export const RECEIVE_VACANCIES = 'RECEIVE_VACANCIES';
